name: Pull request workflow

on:
  pull_request:
    branches:
      - '**'

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
            node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Build @fold-dev/design
        run: npm --workspace @fold-dev/design run build:prod
      - name: Build @fold-dev/core
        run: npm --workspace @fold-dev/core run build:prod
      - name: Run tests
        run: npm test
